<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BeautyExpertsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('beauty_experts')->insert([
            'name' => 'lama Beauty Expert',
            'email' => 'lama@gmail.com',
            'address' => 'irbid',
            'phone' => '0772784927',
            'password' => bcrypt('password'),
            'working_hours' => '{"1":"sunday","2":"tuesday"}',
            'availability' => '{"1":"1:30","2":"5:30"}',
            'service_area' => 'Example Area',
            'services_offered' => 'Service A, Service B',
            'description' => 'Experienced in providing exquisite henna services for various occasions.',
            'image1'=>'download (1).jfif',
            'image2'=>'22.PNG',
            'image3'=>'Latest Mehendi Design Ideas for 2021! - VenueLook Blog.jfif',
            'image4'=>'download (12).jfif',
           'image5'=>'10 Popular Chinese Drama From 2016 Which Are Worth Watching.jfif',
            'service_id' => 1,
            'price' => 10.00,
            'user_id' => 1,
            'average_rating'=>4,
            'expertise'=>7,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('beauty_experts')->insert([
            'name' => 'rahaf Beauty Expert',
            'email' => 'rahaf@gmail.com',
            'address' => 'irbid',
            'phone' => '0772784927',
            'password' => bcrypt('password'),
            'working_hours' => '{"1":"sunday","2":"tuesday"}',
            'availability' => '{"1":"1:30","2":"5:30"}',
            'service_area' => 'Example Area',
            'services_offered' => 'Service A, Service B',
            'description' => 'Experienced in providing exquisite henna services for various occasions.',
            'image1'=>'download.jfif',
            'image2'=>'22.PNG',
            'image3'=>'Latest Mehendi Design Ideas for 2021! - VenueLook Blog.jfif',
            'image4'=>'download (12).jfif',
           'image5'=>'10 Popular Chinese Drama From 2016 Which Are Worth Watching.jfif',
            'service_id' => 1,
            'price' => 10.00,
            'user_id' => 1,
            'expertise'=>4,
            'average_rating'=>5,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('beauty_experts')->insert([
            'name' => 'razan Beauty Expert',
            'email' => 'razan@gmail.com',
            'address' => 'irbid',
            'phone' => '0772784927',
            'password' => bcrypt('password'),
            'working_hours' => '{"1":"sunday","2":"tuesday"}',
            'availability' => '{"1":"1:30","2":"5:30"}',
            'service_area' => 'Example Area',
            'services_offered' => 'Service A, Service B',
            'description' => 'Experienced in providing exquisite henna services for various occasions.',
            'image1'=>'ENSAIO CORPORATIVOS_ Fotos de maquiadora_.jfif',
            'image2'=>'22.PNG',
            'image3'=>'Latest Mehendi Design Ideas for 2021! - VenueLook Blog.jfif',
            'image4'=>'download (12).jfif',
           'image5'=>'10 Popular Chinese Drama From 2016 Which Are Worth Watching.jfif',
            'service_id' => 1,
            'price' => 10.00,
            'user_id' => 1,
            'average_rating'=>4,
            'expertise'=>10,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('beauty_experts')->insert([
            'name' => 'sara Beauty Expert',
            'email' => 'sara@gmail.com',
            'address' => 'irbid',
            'phone' => '0772784927',
            'password' => bcrypt('password'),
            'working_hours' => '{"1":"sunday","2":"tuesday"}',
            'availability' => '{"1":"1:30","2":"5:30"}',
            'service_area' => 'Example Area',
            'services_offered' => 'Service A, Service B',
            'description' => 'Experienced in providing exquisite henna services for various occasions.',
            'image1'=>'ma1.jfif',
            'image2'=>'22.PNG',
            'image3'=>'Latest Mehendi Design Ideas for 2021! - VenueLook Blog.jfif',
            'image4'=>'download (12).jfif',
           'image5'=>'10 Popular Chinese Drama From 2016 Which Are Worth Watching.jfif',
            'service_id' => 1,
            'price' => 10.00,
            'user_id' => 1,
            'average_rating'=>3,
            'expertise'=>4,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('beauty_experts')->insert([
            'name' => 'rama Beauty Expert',
            'email' => 'rama@gmail.com',
            'address' => 'irbid',
            'phone' => '0772784927',
            'password' => bcrypt('password'),
            'working_hours' => '{"1":"sunday","2":"tuesday"}',
            'availability' => '{"1":"1:30","2":"5:30"}',
            'service_area' => 'Example Area',
            'services_offered' => 'Service A, Service B',
            'description' => 'Experienced in providing exquisite henna services for various occasions.',
            'image1'=>'ma7.jfif',
            'image2'=>'22.PNG',
            'image3'=>'Latest Mehendi Design Ideas for 2021! - VenueLook Blog.jfif',
            'image4'=>'download (12).jfif',
           'image5'=>'10 Popular Chinese Drama From 2016 Which Are Worth Watching.jfif',
            'service_id' => 1,
            'price' => 10.00,
            'user_id' => 1,
            'average_rating'=>4,
            'expertise'=>4,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('beauty_experts')->insert([
            'name' => 'lama Beauty Expert',
            'email' => 'lamaa@gmail.com',
            'address' => 'irbid',
            'phone' => '0772784927',
            'password' => bcrypt('password'),
            'working_hours' => '{"1":"sunday","2":"tuesday"}',
            'availability' => '{"1":"1:30","2":"5:30"}',
            'service_area' => 'Example Area',
            'services_offered' => 'Service A, Service B',
            'description' => 'Experienced in providing exquisite henna services for various occasions.',
            'image1'=>'download (1).jfif',
            'image2'=>'d4.jfif',
            'image3'=>'d5.jfif',
            'image4'=>'d2.jfif',
           'image5'=>'d1.jfif',
            'service_id' => 4,
            'price' => 10.00,
            'user_id' => 1,
            'average_rating'=>4,
            'expertise'=>7,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('beauty_experts')->insert([
            'name' => 'rahaf Beauty Expert',
            'email' => 'rahafa@gmail.com',
            'address' => 'irbid',
            'phone' => '0772784927',
            'password' => bcrypt('password'),
            'working_hours' => '{"1":"sunday","2":"tuesday"}',
            'availability' => '{"1":"1:30","2":"5:30"}',
            'service_area' => 'Example Area',
            'services_offered' => 'Service A, Service B',
            'description' => 'Experienced in providing exquisite henna services for various occasions.',
            'image1'=>'download.jfif',
            'image2'=>'d4.jfif',
            'image3'=>'d5.jfif',
            'image4'=>'d2.jfif',
           'image5'=>'d1.jfif',
            'service_id' => 4,
            'price' => 10.00,
            'user_id' => 1,
            'expertise'=>4,
            'average_rating'=>5,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('beauty_experts')->insert([
            'name' => 'razan Beauty Expert',
            'email' => 'razana@gmail.com',
            'address' => 'irbid',
            'phone' => '0772784927',
            'password' => bcrypt('password'),
            'working_hours' => '{"1":"sunday","2":"tuesday"}',
            'availability' => '{"1":"1:30","2":"5:30"}',
            'service_area' => 'Example Area',
            'services_offered' => 'Service A, Service B',
            'description' => 'Experienced in providing exquisite henna services for various occasions.',
            'image1'=>'ENSAIO CORPORATIVOS_ Fotos de maquiadora_.jfif',
            'image2'=>'d4.jfif',
            'image3'=>'d5.jfif',
            'image4'=>'d2.jfif',
           'image5'=>'d1.jfif',
            'service_id' => 4,
            'price' => 10.00,
            'user_id' => 1,
            'average_rating'=>4,
            'expertise'=>10,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('beauty_experts')->insert([
            'name' => 'sara Beauty Expert',
            'email' => 'saraa@gmail.com',
            'address' => 'irbid',
            'phone' => '0772784927',
            'password' => bcrypt('password'),
            'working_hours' => '{"1":"sunday","2":"tuesday"}',
            'availability' => '{"1":"1:30","2":"5:30"}',
            'service_area' => 'Example Area',
            'services_offered' => 'Service A, Service B',
            'description' => 'Experienced in providing exquisite henna services for various occasions.',
            'image1'=>'ma1.jfif',
            'image2'=>'d4.jfif',
            'image3'=>'d5.jfif',
            'image4'=>'d2.jfif',
           'image5'=>'d1.jfif',
            'service_id' => 4,
            'price' => 10.00,
            'user_id' => 1,
            'average_rating'=>3,
            'expertise'=>4,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('beauty_experts')->insert([
            'name' => 'rama Beauty Expert',
            'email' => 'ramaa@gmail.com',
            'address' => 'irbid',
            'phone' => '0772784927',
            'password' => bcrypt('password'),
            'working_hours' => '{"1":"sunday","2":"tuesday"}',
            'availability' => '{"1":"1:30","2":"5:30"}',
            'service_area' => 'Example Area',
            'services_offered' => 'Service A, Service B',
            'description' => 'Experienced in providing exquisite henna services for various occasions.',
            'image1'=>'ma7.jfif',
            'image2'=>'d4.jfif',
            'image3'=>'d5.jfif',
            'image4'=>'d2.jfif',
           'image5'=>'d1.jfif',
            'service_id' => 4,
            'price' => 10.00,
            'user_id' => 1,
            'average_rating'=>4,
            'expertise'=>4,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }
}
